// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PSSC.Sales.Api.Infrastructure.Persistence;

#nullable disable

namespace PSSC.Sales.Api.Migrations
{
    [DbContext(typeof(SalesDbContext))]
    [Migration("20251201181719_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PSSC.Sales.Api.Infrastructure.Persistence.Entities.OrderEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CalculatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("CustomerId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("PlacedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("ValidatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("OrderNumber")
                        .IsUnique();

                    b.HasIndex("PlacedAt");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("PSSC.Sales.Api.Infrastructure.Persistence.Entities.OrderLineEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ProductCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("OrderId");

                    b.HasIndex("ProductCode");

                    b.ToTable("OrderLines");
                });

            modelBuilder.Entity("PSSC.Sales.Api.Infrastructure.Persistence.Entities.ProductEntity", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("StockQuantity")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Code");

                    b.HasIndex("IsActive");

                    b.HasIndex("Name");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Code = "BOOK-001",
                            CreatedAt = new DateTime(2025, 12, 1, 18, 17, 17, 863, DateTimeKind.Utc).AddTicks(6753),
                            Description = "A Handbook of Agile Software Craftsmanship by Robert C. Martin",
                            IsActive = true,
                            Name = "Clean Code",
                            Price = 89.99m,
                            StockQuantity = 100
                        },
                        new
                        {
                            Code = "BOOK-002",
                            CreatedAt = new DateTime(2025, 12, 1, 18, 17, 17, 863, DateTimeKind.Utc).AddTicks(6921),
                            Description = "Tackling Complexity in the Heart of Software by Eric Evans",
                            IsActive = true,
                            Name = "Domain-Driven Design",
                            Price = 119.99m,
                            StockQuantity = 50
                        },
                        new
                        {
                            Code = "BOOK-003",
                            CreatedAt = new DateTime(2025, 12, 1, 18, 17, 17, 863, DateTimeKind.Utc).AddTicks(6923),
                            Description = "Your Journey to Mastery by David Thomas and Andrew Hunt",
                            IsActive = true,
                            Name = "The Pragmatic Programmer",
                            Price = 99.99m,
                            StockQuantity = 75
                        },
                        new
                        {
                            Code = "BOOK-004",
                            CreatedAt = new DateTime(2025, 12, 1, 18, 17, 17, 863, DateTimeKind.Utc).AddTicks(6924),
                            Description = "Improving the Design of Existing Code by Martin Fowler",
                            IsActive = true,
                            Name = "Refactoring",
                            Price = 109.99m,
                            StockQuantity = 60
                        },
                        new
                        {
                            Code = "BOOK-005",
                            CreatedAt = new DateTime(2025, 12, 1, 18, 17, 17, 863, DateTimeKind.Utc).AddTicks(6926),
                            Description = "Elements of Reusable Object-Oriented Software by Gang of Four",
                            IsActive = true,
                            Name = "Design Patterns",
                            Price = 129.99m,
                            StockQuantity = 40
                        });
                });

            modelBuilder.Entity("PSSC.Sales.Api.Infrastructure.Persistence.Entities.OrderLineEntity", b =>
                {
                    b.HasOne("PSSC.Sales.Api.Infrastructure.Persistence.Entities.OrderEntity", "Order")
                        .WithMany("Lines")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Order");
                });

            modelBuilder.Entity("PSSC.Sales.Api.Infrastructure.Persistence.Entities.OrderEntity", b =>
                {
                    b.Navigation("Lines");
                });
#pragma warning restore 612, 618
        }
    }
}
